--- 
abstract: A POE filter for talking with SlimServer over CLI
author: Andy Grundman <andy@slimdevices.com>
build_requires: 
  Test::More: 0.47
  Test::Perl::Critic: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-Slim-CLI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Clone: 0
  POE: 0.38
  URI: 0
  perl: 5.6.1
version: 0.02
